apiVersion: v1
kind: Service
metadata:
  name: postgres-n8n
spec:
  type: ClusterIP
  selector:
    app: postgres-n8n
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
    - port: 5678
      targetPort: 5678
      nodePort: 32536
