apiVersion: v1
kind: Service
metadata:
  name: postgres-n8n
  namespace: n8n
  labels:
    app.kubernetes.io/instance: n8n
spec:
  type: ClusterIP
  selector:
    service: postgres-n8n
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  type: NodePort
  selector:
    service: n8n
  ports:
    - port: 5678
      targetPort: 5678
      nodePort: 32536
